apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-cpu-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ollama.pvcSize }}
  storageClassName: "standard"



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-gpu-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ollama.pvcSize }}
  storageClassName: "standard"