apiVersion: v1
kind: Service
metadata:
  name: ollama-cpu
spec:
  selector:
    app: ollama-cpu
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-gpu
spec:
  selector:
    app: ollama-gpu
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
